config/routes.rb
Rails.application.routes.draw do
  root to: 'activities#index'
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }
  devise_scope :user do
    post 'set_email', to: 'oauth_callbacks#set_email'
  end
  resources :users, only: :show do
    resources :demotracks, only: %i[create destroy], shallow: true
    resources :posts, only: %i[create destroy], shallow: true
  end

  resources :activities, only: :index

  resources :conversations, only: :index
  resources :messages, only: %i[index create]
  resources :communities do
    resources :posts, only: %i[create destroy], shallow: true
  end

  resources :spotify_tracks, only: %i[create destroy]

  get 'search_tracks', to: 'spotify_tracks#search_tracks'
  get 'search', to: 'search#search'

  match :follow, to: 'follows#create', as: :follow, via: :post
  match :unfollow, to: 'follows#destroy', as: :unfollow, via: :post

  mount ActionCable.server => '/cable'
end

app/models/demotrack.rb
class Demotrack < ApplicationRecord
  include PublicActivity::Model
  tracked only: :create, owner: ->(controller, _model) { controller && controller.current_user }

  belongs_to :user, touch: true
  has_one_attached :audio
  validates :audio, blob: { content_type: :audio, size_range: 0..5.megabytes }
end

app/controllers/demotracks_controller.rb
class DemotracksController < ApplicationController
  before_action :authenticate_user!
  before_action :demotrack, only: :destroy
  before_action :user, only: :create

  authorize_resource

  def create
    @demotrack = @user.demotracks.new
    @demotrack.audio.attach(params[:demotrack])
    redirect_to @user, alert: t('demotracks.format_error') unless @demotrack.save
  end

  def destroy
    @demotrack.destroy
  end

  private

  def demotrack
    @demotrack ||= Demotrack.find(params[:id])
  end

  def user
    @user ||= User.find(params[:user_id])
  end
end

app/views/demotracks/_demotrack.html.slim
.container
  .row
    - if demotrack.audio.attached?
      p.col-6.bg-white.section id = "demotrack-#{demotrack.id}"
        = link_to demotrack.audio.filename.to_s, url_for(demotrack.audio), class: 'text-success'
        br
        audio(controls)
          source src="#{rails_blob_url(demotrack.audio)}" type="#{demotrack.audio.content_type}"
        br
        = link_to t('.delete_track'), demotrack_path(demotrack), method: :delete, class: "btn btn-outline-success btn-sm mb-2", remote: true if can? :destroy, demotrack
      .col-6

app/views/demotracks/_form.html.slim
.new_demotrack
  p #{t('.add_demotrack_info')}
  = form_with url: user_demotracks_path(resource), local: false do |f|
    p
      = f.label :demotrack, t('.new_demotrack')
      = f.file_field :demotrack
      = f.submit t('.add_demotrack')

app/views/demotracks/create.js.erb
$('.demotracks').html('<%= render @user.demotracks %>');
$('.flash-notice').empty();

app/views/demotracks/destroy.js.erb
$('#demotrack-' + <%= @demotrack.id %>).remove();