config/routes.rb
Rails.application.routes.draw do
  root to: 'activities#index'
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }
  devise_scope :user do
    post 'set_email', to: 'oauth_callbacks#set_email'
  end
  resources :users, only: :show do
    resources :demotracks, only: %i[create destroy], shallow: true
    resources :posts, only: %i[create destroy], shallow: true
  end

  resources :activities, only: :index

  resources :conversations, only: :index
  resources :messages, only: %i[index create]
  resources :communities do
    resources :posts, only: %i[create destroy], shallow: true
  end

  resources :spotify_tracks, only: %i[create destroy]

  get 'search_tracks', to: 'spotify_tracks#search_tracks'
  get 'search', to: 'search#search'

  match :follow, to: 'follows#create', as: :follow, via: :post
  match :unfollow, to: 'follows#destroy', as: :unfollow, via: :post

  mount ActionCable.server => '/cable'
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  belongs_to :user

  validates :body, :conversation_id, :user_id, presence: true
  scope :unread, ->(current_user) { where('user_id != ? AND read = ?', current_user.id, false) }

  def self.read(current_user)
    unread(current_user).update_all(read: true)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!
  authorize_resource

  before_action :conversation, only: %i[index create]
  after_action :publish_message, only: :create

  def index
    @messages = @conversation.messages.order(created_at: :asc)
    @messages.read(current_user)
  end

  def create
    @message = @conversation.messages.new(message_params)
    @message.body = params[:body] if params[:body]
    @message.user = current_user
    @message.save
  end

  private

  def message_params
    params.permit(:body)
  end

  def conversation
    if params[:conversation_id]
      @conversation ||= Conversation.find(params[:conversation_id])
    else
      conversation = Conversation.between(params[:sender_id], params[:receiver_id])
      @conversation = if conversation.present?
                        conversation.first
                      else
                        Conversation.create(conversation_params)
                      end

    end
    gon.conversation_id = @conversation.id
    gon.user_id = current_user.id if current_user
  end

  def conversation_params
    params.permit(:sender_id, :receiver_id)
  end

  def publish_message
    return if @message.errors.any?

    avatar = url_for(@message.user.avatar) if @message.user.avatar.blob

    ActionCable.server.broadcast(
      "conversation-#{@conversation.id}-messages",
      message: @message,
      user_id: @message.user.id,
      email: @message.user.email,
      avatar: avatar,
      time: @message.time
    )
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.slim
button type="button" class="btn btn-outline-success" data-toggle="modal" data-target="#exampleModal" #{t('.send_message')}
div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true"
  div class="modal-dialog" role="document"
    div class="modal-content"
      .successful_response
        div class="modal-header"
          h5 class="modal-title" id="exampleModalLabel" #{t('.new_message')}
          button type="button" class="close" data-dismiss="modal" aria-label="Close"
            span aria-hidden="true"&times
        div class="modal-body"
          = form_tag messages_path(sender_id: current_user.id, receiver_id: resource.id), method: :post, class: "form-group", remote: true do
            = text_area_tag :body, nil, placeholder: t('.your_message'), class: "form-control"
            = submit_tag t('.send'), class: "form-control btn btn-outline-success"

app/views/messages/_message.html.slim
.media.bg-white
  li.list-group-item
    .media-left
      - if message.user.avatar.attached?
        = image_tag message.user.avatar.variant(resize: "50x50!"), class: "rounded-circle"
      - else
        = image_pack_tag "media/images/default_avatar.png", style: "height: 50px; weight: 50px", class: "rounded-circle"
    .media-body
      h5.media-heading
        = message.user.email
        small.text-muted
          = message.time
      p
        = message.body

app/views/messages/create.js.erb
$(".messages").append('<%= j render @message %>');
$('.successful_response').html( "<p class='text-success text-center mt-2'>Message is succesfull created</p>" );

app/views/messages/index.html.slim
ul.list-group.list-group-flush.messages
  = render @messages

= form_tag messages_path(conversation_id: @conversation.id), method: :post, class: "form-group", remote: true do
  = text_area_tag :body, nil, placeholder: t('.your_message'), class: "form-control"
  = submit_tag t('.send'), class: "btn btn-outline-success "