config/routes.rb
Rails.application.routes.draw do
  root to: 'activities#index'
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }
  devise_scope :user do
    post 'set_email', to: 'oauth_callbacks#set_email'
  end
  resources :users, only: :show do
    resources :demotracks, only: %i[create destroy], shallow: true
    resources :posts, only: %i[create destroy], shallow: true
  end

  resources :activities, only: :index

  resources :conversations, only: :index
  resources :messages, only: %i[index create]
  resources :communities do
    resources :posts, only: %i[create destroy], shallow: true
  end

  resources :spotify_tracks, only: %i[create destroy]

  get 'search_tracks', to: 'spotify_tracks#search_tracks'
  get 'search', to: 'search#search'

  match :follow, to: 'follows#create', as: :follow, via: :post
  match :unfollow, to: 'follows#destroy', as: :unfollow, via: :post

  mount ActionCable.server => '/cable'
end

app/models/follow.rb
class Follow < ApplicationRecord
  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  # NOTE: Follows belong to the "followable" and "follower" interface
  belongs_to :followable, polymorphic: true
  belongs_to :follower,   polymorphic: true

  def block!
    update(blocked: true)
  end
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  before_action :authenticate_user!
  before_action :resource, only: %i[create destroy]
  authorize_resource

  def create
    current_user.follow(@resource)
  end

  def destroy
    current_user.stop_following(@resource)
  end

  private

  def resource
    @klass = [Community, User].find { |klass| params["#{klass.name.underscore}_id"] }
    @resource = @klass.find(params["#{@klass.name.underscore}_id"])
  end
end

app/helpers/follows_helper.rb
module FollowsHelper
  def resource_class_name(resource)
    resource.class.name.underscore
  end
end

app/views/follows/_follows_count.html.slim
.follows-count
  .row.mt-4
    .col-4
      h4
        = resource.followers_count
      h5
        = t('follows.follows_count.followers')
    .col-4
      - unless resource.class.name.eql?("Community")
        h4
          = resource.following_user_count
        h5
          = t('follows.follows_count.follow')

app/views/follows/_form.html.slim
.follow-button
  - if resource.followed_by?(current_user)
    = form_tag unfollow_path("#{resource_class_name(resource)}_id" => resource.id), method: :post, remote: true do
      = button_tag t('.unfollow'), class: 'btn btn-outline-success'
  - else
    = form_tag follow_path("#{resource_class_name(resource)}_id" => resource.id), method: :post, remote: true do
      = button_tag t('.follow'), class: 'btn btn-outline-success'

app/views/follows/create.js.erb
$('.follows-count').html('<%= render 'follows/follows_count', resource: @resource %>');
$('.follow-button').html('<%= render 'follows/form', resource: @resource %>');

app/views/follows/destroy.js.erb
$('.follows-count').html('<%= render 'follows/follows_count', resource: @resource %>');
$('.follow-button').html('<%= render 'follows/form', resource: @resource %>');