config/routes.rb
Rails.application.routes.draw do
  root to: 'activities#index'
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }
  devise_scope :user do
    post 'set_email', to: 'oauth_callbacks#set_email'
  end
  resources :users, only: :show do
    resources :demotracks, only: %i[create destroy], shallow: true
    resources :posts, only: %i[create destroy], shallow: true
  end

  resources :activities, only: :index

  resources :conversations, only: :index
  resources :messages, only: %i[index create]
  resources :communities do
    resources :posts, only: %i[create destroy], shallow: true
  end

  resources :spotify_tracks, only: %i[create destroy]

  get 'search_tracks', to: 'spotify_tracks#search_tracks'
  get 'search', to: 'search#search'

  match :follow, to: 'follows#create', as: :follow, via: :post
  match :unfollow, to: 'follows#destroy', as: :unfollow, via: :post

  mount ActionCable.server => '/cable'
end

app/models/spotify_track.rb
class SpotifyTrack < ApplicationRecord
  belongs_to :user, touch: true
  validates :name, :spotify_id, :artists, :image, :preview, presence: true
  validates :spotify_id, uniqueness: { scope: :user }

  def self.add_new(spotify_track)
    create(
      spotify_id: spotify_track.id,
      name: spotify_track.name,
      artists: spotify_track.artists[0].name,
      image: spotify_track.album.images[0]['url'],
      preview: spotify_track.preview_url
    )
  end
end

app/controllers/spotify_tracks_controller.rb
class SpotifyTracksController < ApplicationController
  protect_from_forgery except: :search_tracks
  before_action :authenticate_user!
  before_action :track, only: :destroy
  skip_authorization_check

  def search_tracks
    @tracks = RSpotify::Track.search(params[:track_name]) unless params[:track_name].eql?('')
  end

  def create
    @spotify_track = RSpotify::Track.find(params[:track_id])
    @track = current_user.spotify_tracks.add_new(@spotify_track)
  end

  def destroy
    authorize! :destroy, @track
    @track.destroy
  end

  private

  def track
    @track ||= SpotifyTrack.find(params[:id])
  end
end

app/helpers/spotify_tracks_helper.rb
module SpotifyTracksHelper
end

app/views/spotify_tracks/_found_tracks.html.slim
.container
  .row
    - if resource
      - resource.each do | track |
        - if track.preview_url
          p.col.bg-white.border.section id = "found-spotify-track-#{track.id}"
            = image_tag(track.album.images[0]["url"], size: '100', class: 'mt-2')
            br
            = track.artists[0].name
            br
            = track.name
            audio(controls)
              source src="#{track.preview_url}"
            br
            = link_to t('spotify_tracks.add_track'), spotify_tracks_path(track_id: track.id),
                    method: :post, class: "btn btn-outline-success btn-sm mb-2", remote: true

app/views/spotify_tracks/_search.html.slim
p.mt-3.text-justify #{t('.search_track')}
= form_tag search_tracks_path, method: "get", html: { class: "form " }, remote: true do
  = text_field_tag(:track_name, "", placeholder: "#{t('.enter_track_name')}", class: "form-control")
  = submit_tag "#{t('.search')}", class: "btn btn-success mt-2 mb-2"

app/views/spotify_tracks/_spotify_track.html.slim
.container
  .row
    p.col-6.bg-white.section id = "spotify-track-#{spotify_track.id}"
      = image_tag(spotify_track.image, size: '100', class: 'mt-2')
      br
      = spotify_track.artists
      br
      = spotify_track.name
      br
      audio(controls)
        source src="#{spotify_track.preview}"
      br
      = link_to t('spotify_tracks.spotify_track.delete_track'), spotify_track_path(spotify_track),
              class: "btn btn-outline-success btn-sm mb-2", method: :delete, remote: true if can? :destroy, spotify_track
    .col-6

app/views/spotify_tracks/create.js.erb
$('.spotify-tracks-errors-' + <%= current_user.id %>).html('<%= render 'shared/errors', resource: @track %>');
$('.tracks-' + <%= current_user.id %>).html('<%= render current_user.spotify_tracks %>');

app/views/spotify_tracks/destroy.js.erb
$('#spotify-track-' + <%= @track.id %>).remove();

app/views/spotify_tracks/search_tracks.js.erb
$('.found-spotify-tracks').html('<%= render 'spotify_tracks/found_tracks', resource: @tracks %>');